# thisd is the name of workflow show in github actions
name: CICD

# this is manual deliver workflow  whenver usee need
on: workflow_dispatch

jobs:

code:
  runs-on: ubuntu-latest
  steps:
    - name: checkout code
      run: echo "code clone from github"
build:
  runs-on: ubuntu-latest
  steps:
    - name: build docker container
      run: echo " docker container build"
test:
  runs-on: ubuntu-latest
  step:
    - name: test the container
      run: echo "testing the container"
deploy:
  runs-on: ubuntu-latest
  steps:
    - name: deploying the app
      run: echo " docker compse deploy the app'
