  name: Bilal

on: 
push:
 branches: [master]  
jobs:

   greet:
   runs-on: ubuntu-latest
    steps:
     - name: say hello typ users
      run: "hello dosto"

      - name: say hello to username
         run:  echo "hello $USER"
     
  
